server:
  port: 8080

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book_portal
    username: daria
    password: mypassword # Replace with your actual database credentials
  jpa:
    defer-datasource-initialization: update
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        globally_quoted_identifiers: true
        enable_lazy_load_no_trans: true
  sql:
    init:
      mode: always